_includes/analytics.html
=> google analytics

_posts/2020-3-20-chapter0.md, _posts/2020-3-21-chapter1.md, _posts/2020-3-22-chapter2.md, _posts/2020-3-23-chapter3.md, _posts/2020-3-24-chapter4.md, _posts/2020-3-25-chapter5.md, _posts/2020-3-26-chapter6.md, _posts/2020-3-27-chapter7.md
=> Create all the pages

_posts/2020-3-25-chapter6-mac-gcc.md, _posts/2020-3-25-chapter6-mac-xcode.md, _posts/2020-3-25-chapter6-ubuntu-virtualmachine.md, _posts/2020-3-25-chapter6-virtualbox-mac.md, _posts/2020-3-25-chapter6-virtualbox-windows.md, _posts/2020-3-25-chapter6-windows-mingw.md, _posts/2020-3-25-chapter6-windows-visualstudio.md, _posts/2020-3-25-chapter6.md
Chapter6に環境ごとのインストール方法を記載するページを作成した。
=> Create Subpages on Chapter 6

_posts/2020-3-25-chapter6.md
chapter6の中心ページにてリンクの形式が間違っていたため修正
=> fix link on chapter6.md

_posts/2020-3-25-chapter6-mac-xcode.md
=> Updated quotes

_posts/2020-3-25-chapter6-mac-xcode.md
=> Changed the quotes

_posts/2020-3-22-chapter3-2-apg4b.md
=> Added sentence for Mathjax to chapter3-2

.gitignore
I added to .gitignore followings:
- .DS_Store
- .ini
=> Add the file names which should be ignored to .gitignore

_posts/2020-3-25-chapter6-mac-xcode.md
=> changed the settings of the images

_posts/2020-3-25-chapter6-mac-xcode.md
=> fixed the settings of the images

static/css/main.css
=> tableの枠線を表示

_config.yml
Disqusでゲストコメントができるようになった...はず?
=> fix disqus

_layouts/post.html, _layouts/posts_by_category.html
=> fix 404 error on localhost

_posts/2020-3-23-chapter4.md
リンク増やしました。
各リンクの下に説明書いてます。
あとProblemsのところ画像と文が入り乱れて見にくいと思ったので
水平線をいくつか新しく入れました。
よろしくお願いします。
=> Added links of AOJ,Qiita,and some articles in Qiita.

_config.yml
=> sitemapが壊れているのが多分urlのせいなので直しました

feed.xml, sitemap.xml
=> Fix sitemap

_layouts/page.html
=> add-disqus-form

static/js/super-search.js
object(feed.xml)を検索結果に出てこないよう、invalid dateを表示しないようにしました
=> Fix search

_includes/meta.html
=> fixed image URL

_config.yml
=> chenge about and desc

others/lecture1.md
=> fix implementation

.github/workflows/main.yml
=> fix branch name
